(function(){
"use strict";
const STORAGE_KEY="wgangPortalV073";
const LEGACY_KEYS=["wgangPortalV071","wgangPortalV07"];
const TASK_TYPES=(window.ROOSTER_DATA&&window.ROOSTER_DATA.taskTypes)||["Melk","Bacon","Egg","Geitemelk","Ull","Høsting","Produksjon","Lastebil","Båt","By","Fisk","Gruve","Hjelpeoppgaver"];
const PREF_LABELS={like:"Liker",can:"Kan ta",avoid:"Helst ikke",no:"Kan ikke"};
const seed={
  accounts:[
    {id:"owner-1",name:"Leder",email:"admin@wgang.no",password:"WGANG2026",role:"owner",approved:true,choice:"joined",preferences:{By:"like",Gruve:"can",Båt:"avoid",Produksjon:"like"}},
    {id:"member-1",name:"Nabo",email:"nabo@wgang.no",password:"WGANG2026",role:"member",approved:true,choice:"unsure",preferences:{Melk:"like",Bacon:"like",Hjelpeoppgaver:"can",Båt:"avoid"}},
    {id:"member-2",name:"Solglimt",email:"sol@wgang.no",password:"WGANG2026",role:"member",approved:true,choice:"pause",preferences:{Fisk:"like",Båt:"like",Gruve:"no"}},
    {id:"pending-1",name:"FarmFryd",email:"farmfryd@example.com",password:"WGANG2026",role:"member",approved:false,choice:"waiting",preferences:{}}
  ],
  derby:{type:"Standard Derby",taskTotal:9,maxPoints:320,strategy:["Ta kun oppgaver med 320 poeng i Standard Derby.","Admin rydder bort oppgaver nabolaget sjelden ønsker, slik at tavla holdes i bevegelse.","Bruk medlemmenes oppgavepreferanser for å vite hvilke 320-oppgaver som bør få stå litt."]},
  currentUserId:null
};
const clone=x=>JSON.parse(JSON.stringify(x));
function normalize(x){
  if(!x||!Array.isArray(x.accounts)) return clone(seed);
  x.accounts.forEach(a=>{if(!a.preferences||typeof a.preferences!=="object")a.preferences={};});
  if(!x.derby)x.derby=clone(seed.derby);
  if(!Array.isArray(x.derby.strategy))x.derby.strategy=clone(seed.derby.strategy);
  return x;
}
function load(){
  try{
    let raw=localStorage.getItem(STORAGE_KEY);
    if(!raw){
      for(const key of LEGACY_KEYS){raw=localStorage.getItem(key);if(raw)break;}
    }
    return raw?normalize(JSON.parse(raw)):clone(seed);
  }catch(e){return clone(seed);}
}
let state=load();
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){console.warn("Kunne ikke lagre lokalt",e);}}
const $=id=>document.getElementById(id), $$=s=>document.querySelectorAll(s);
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const landing=$("landing"),portal=$("portal"),sidebar=$("sidebar"),portalMain=$("portalMain"),auth=$("authDialog");
function current(){return state.accounts.find(a=>a.id===state.currentUserId)||null;}
function isAdmin(u=current()){return !!u&&["owner","admin"].includes(u.role);}
function showDialog(d){if(d&&typeof d.showModal==="function")d.showModal();else if(d)d.setAttribute("open","");}
function closeDialog(d){if(d&&typeof d.close==="function")d.close();else if(d)d.removeAttribute("open");}
function openAuth(tab="login"){showDialog(auth);setAuthTab(tab);}
function setAuthTab(tab){$$('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));$('loginForm').classList.toggle('hidden',tab!=="login");$('registerForm').classList.toggle('hidden',tab!=="register");$('authTitle').textContent=tab==="login"?"Logg inn":"Søk om medlemskap";$('authIntro').textContent=tab==="login"?"Bruk e-postadressen din for å åpne portalen.":"Bruk Hay Day-navnet ditt. En administrator godkjenner søknaden.";}
function openPortal(){const u=current();if(!u){openAuth();return;}landing.classList.add("hidden");portal.classList.remove("hidden");portal.setAttribute("aria-hidden","false");document.body.classList.toggle("admin-mode",isAdmin(u));renderSession();navigate("dashboard",false);window.scrollTo(0,0);}
function logout(){state.currentUserId=null;save();portal.classList.add("hidden");portal.setAttribute("aria-hidden","true");landing.classList.remove("hidden");document.body.classList.remove("admin-mode");sidebar.classList.remove("open");location.hash="landing";window.scrollTo(0,0);}
function navigate(route,hash=true){if(route==="admin"&&!isAdmin())route="dashboard";$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===route));$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));sidebar.classList.remove('open');if(hash)location.hash=route;portalMain.focus();window.scrollTo({top:0,behavior:'smooth'});}

$('openPortalTop').onclick=()=>openAuth('login');$('openPortalHero').onclick=()=>openAuth('login');$('openPortalRule').onclick=()=>openAuth('login');$('joinDemoButton').onclick=()=>openAuth('register');$('closeAuth').onclick=()=>closeDialog(auth);$('closePortal').onclick=logout;
$$('[data-auth-tab]').forEach(b=>b.onclick=()=>setAuthTab(b.dataset.authTab));
$('loginForm').onsubmit=e=>{e.preventDefault();const email=$('loginEmail').value.trim().toLowerCase(),pw=$('loginPassword').value.trim();const u=state.accounts.find(a=>a.email.toLowerCase()===email&&a.password===pw);const msg=$('loginMessage');msg.classList.remove('success');if(!u){msg.textContent='Feil e-post eller passord.';return;}if(!u.approved){msg.textContent='Søknaden din venter fortsatt på godkjenning.';return;}state.currentUserId=u.id;save();closeDialog(auth);msg.textContent='';openPortal();};
$('registerForm').onsubmit=e=>{e.preventDefault();const name=$('registerName').value.trim(),email=$('registerEmail').value.trim().toLowerCase(),pw=$('registerPassword').value,msg=$('registerMessage');msg.classList.remove('success');if(state.accounts.some(a=>a.email.toLowerCase()===email)){msg.textContent='Denne e-postadressen er allerede registrert.';return;}if(state.accounts.some(a=>a.name.toLowerCase()===name.toLowerCase())){msg.textContent='Dette Hay Day-navnet er allerede registrert.';return;}state.accounts.push({id:'user-'+Date.now(),name,email,password:pw,role:'member',approved:false,choice:'waiting',preferences:{}});save();msg.textContent='Søknaden er sendt. En administrator må godkjenne deg før innlogging.';msg.classList.add('success');e.target.reset();renderAdmin();};
$$('[data-route]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();if(portal.classList.contains('hidden')){openPortal();return;}navigate(a.dataset.route);}));$('menuToggle').onclick=()=>sidebar.classList.toggle('open');$('roleSwitch').onclick=()=>navigate('admin');
function roleLabel(r){return {owner:'Eier',admin:'Administrator',member:'Medlem'}[r]||r;}
function choiceLabel(c){return {joined:'Deltar',pause:'Tar pause',unsure:'Usikker',waiting:'Mangler svar'}[c]||c;}
function approved(){return state.accounts.filter(a=>a.approved);}
function topPreferences(a){return TASK_TYPES.filter(t=>['like','can'].includes(a.preferences?.[t])).slice(0,3);}
function renderSession(){const u=current();if(!u)return;$('profileAvatar').textContent=u.name.charAt(0).toUpperCase();$('profileName').textContent=u.name;$('profileRole').textContent=roleLabel(u.role);$('welcomeHeading').textContent='Hei, '+u.name+' 👋';$('accountBadge').textContent=roleLabel(u.role).toUpperCase();$$('.choice-button').forEach(b=>b.classList.toggle('selected',b.dataset.choice===u.choice));$('participationStatus').textContent=u.choice==='joined'?'Du har bekreftet at du deltar.':u.choice==='pause'?'Du tar pause i neste derby.':'Du er registrert som usikker.';$('myStatusMetric').textContent=choiceLabel(u.choice);renderDerbyConfig();renderMetrics();renderMembers();renderPreferences();renderAdmin();}
$$('.choice-button').forEach(b=>b.onclick=()=>{const u=current();if(!u)return;u.choice=b.dataset.choice;save();renderSession();});
function renderMetrics(){const all=approved(),answered=all.filter(a=>['joined','pause','unsure'].includes(a.choice)).length;$('respondedMetric').textContent=answered+'/'+all.length;}
function renderMembers(){const grid=$('memberGrid');if(!grid)return;const q=$('memberSearch').value.trim().toLowerCase(),f=$('memberFilter').value;grid.innerHTML=approved().filter(a=>a.name.toLowerCase().includes(q)&&(f==='all'||a.choice===f)).map(a=>{const prefs=topPreferences(a);return `<article class="member-card"><div class="member-head"><div class="member-identity"><span class="avatar">${esc(a.name[0])}</span><div><h3>${esc(a.name)}</h3><span class="member-role">${roleLabel(a.role)}</span></div></div><span class="member-status status-${a.choice==='unsure'?'waiting':a.choice}">${choiceLabel(a.choice)}</span></div><div class="member-info"><div><span>Neste derby</span><strong>${choiceLabel(a.choice)}</strong></div><div><span>Tilgang</span><strong>Godkjent</strong></div></div>${prefs.length?`<div class="tag-list">${prefs.map(t=>`<span class="task-tag like">${esc(t)}</span>`).join('')}</div>`:'<p class="helper-text">Ingen oppgavepreferanser registrert ennå.</p>'}</article>`;}).join('')||'<p class="empty-state">Ingen medlemmer matcher søket.</p>';}
$('memberSearch').oninput=renderMembers;$('memberFilter').onchange=renderMembers;
function renderPreferences(){const u=current(),list=$('preferenceList');if(!u||!list)return;list.innerHTML=TASK_TYPES.map(t=>`<div class="preference-row"><strong>${esc(t)}</strong><div class="preference-actions">${Object.entries(PREF_LABELS).map(([k,label])=>`<button type="button" data-pref-task="${esc(t)}" data-pref-value="${k}" class="${u.preferences?.[t]===k?'selected':''}">${label}</button>`).join('')}</div></div>`).join('');$$('[data-pref-task]').forEach(b=>b.onclick=()=>{const me=current();if(!me)return;me.preferences=me.preferences||{};if(me.preferences[b.dataset.prefTask]===b.dataset.prefValue)delete me.preferences[b.dataset.prefTask];else me.preferences[b.dataset.prefTask]=b.dataset.prefValue;save();renderPreferences();renderMembers();renderAdminPreferences();});}
function preferenceStats(){const all=approved(),stats={};TASK_TYPES.forEach(t=>stats[t]={like:0,can:0,avoid:0,no:0});all.forEach(a=>Object.entries(a.preferences||{}).forEach(([t,v])=>{if(stats[t]&&stats[t][v]!=null)stats[t][v]++;}));return stats;}
function taskRecommendation(s){const positive=s.like+s.can,negative=s.avoid+s.no;if(s.like>=2)return {label:'La stå',cls:'recommend-keep'};if(positive===0&&negative>0)return {label:'Slett raskt',cls:'recommend-clear'};if(positive===0&&negative===0)return {label:'Ukjent',cls:'recommend-unknown'};if(positive>=negative)return {label:'Kan stå litt',cls:'recommend-watch'};return {label:'Vurder å slette',cls:'recommend-clear'};}
function renderAdminPreferences(){if(!isAdmin())return;const stats=preferenceStats(),rows=TASK_TYPES.map(t=>({t,s:stats[t],r:taskRecommendation(stats[t])}));$('adminPreferenceTable').innerHTML=rows.map(x=>`<tr><td><strong>${esc(x.t)}</strong></td><td>${x.s.like}</td><td>${x.s.can}</td><td>${x.s.avoid}</td><td>${x.s.no}</td><td><span class="recommendation ${x.r.cls}">${x.r.label}</span></td></tr>`).join('');const most=rows.slice().sort((a,b)=>(b.s.like*2+b.s.can)-(a.s.like*2+a.s.can)).slice(0,3);const clear=rows.slice().sort((a,b)=>(b.s.no*2+b.s.avoid)-(a.s.no*2+a.s.avoid)).filter(x=>x.s.no+x.s.avoid>0).slice(0,3);$('adminPreferenceSummary').innerHTML=`<article><span>WGANG liker best</span><strong>${most.map(x=>esc(x.t)).join(', ')||'Ingen data'}</strong><small>Basert på medlemmenes valg</small></article><article><span>Aktuelle å rydde</span><strong>${clear.map(x=>esc(x.t)).join(', ')||'Ingen data'}</strong><small>Bruk som støtte – 320 poeng gjelder fortsatt</small></article>`;}
function renderAdmin(){if(!isAdmin())return;const pending=state.accounts.filter(a=>!a.approved),all=approved();$('pendingMembers').innerHTML=pending.length?pending.map(a=>`<div class="approval-item"><div><strong>${esc(a.name)}</strong><small>${esc(a.email)}</small></div><div class="approval-actions"><button class="button button-primary button-small" data-approve="${a.id}">Godkjenn</button><button class="button button-small button-danger" data-reject="${a.id}">Avslå</button></div></div>`).join(''):'<p class="empty-state">Ingen søknader venter på godkjenning.</p>';
$('accountAdminTable').innerHTML=all.map(a=>`<tr><td><strong>${esc(a.name)}</strong></td><td>${esc(a.email)}</td><td><select class="role-select" data-role-id="${a.id}" ${a.role==='owner'?'disabled':''}><option value="member" ${a.role==='member'?'selected':''}>Medlem</option><option value="admin" ${a.role==='admin'?'selected':''}>Administrator</option><option value="owner" ${a.role==='owner'?'selected':''}>Eier</option></select></td><td>${choiceLabel(a.choice)}</td><td>${a.id===current().id?'<span class="logout-note">Din konto</span>':'<button class="table-action" data-remove="'+a.id+'">Fjern</button>'}</td></tr>`).join('');
const counts={joined:0,pause:0,unsure:0,waiting:0};all.forEach(a=>counts[a.choice]=(counts[a.choice]||0)+1);$('adminStatusGrid').innerHTML=[['Deltar',counts.joined],['Tar pause',counts.pause],['Usikker',counts.unsure],['Mangler svar',counts.waiting]].map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong><small>medlemmer</small></article>`).join('');$('adminResponseBadge').textContent=(all.length-counts.waiting)+' av '+all.length+' svar';renderAdminPreferences();
$$('[data-approve]').forEach(b=>b.onclick=()=>{const a=state.accounts.find(x=>x.id===b.dataset.approve);if(a){a.approved=true;a.choice='unsure';a.preferences=a.preferences||{};save();renderAdmin();renderMetrics();renderMembers();}});$$('[data-reject]').forEach(b=>b.onclick=()=>{state.accounts=state.accounts.filter(x=>x.id!==b.dataset.reject);save();renderAdmin();});$$('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Fjerne medlemmet fra portalen?')){state.accounts=state.accounts.filter(x=>x.id!==b.dataset.remove);save();renderAdmin();renderMetrics();renderMembers();}});$$('[data-role-id]').forEach(s=>s.onchange=()=>{const a=state.accounts.find(x=>x.id===s.dataset.roleId);if(a){a.role=s.value;save();renderAdmin();renderMembers();}});}
const taskRange=$('taskRange');function progress(){const d=+taskRange.value,t=+taskRange.max,p=t?d/t*100:0;$('tasksDone').textContent=d;$('tasksTotal').textContent=t;$('dashboardTasksDone').textContent=d;$('dashboardTasksTotal').textContent=t;$('derbyProgress').style.width=p+'%';$('dashboardProgress').style.width=p+'%';}taskRange.oninput=progress;$('finishDerby').onclick=()=>{taskRange.value=taskRange.max;progress();$('derbyStatus').value='Ferdig';$('finishStatus').textContent='Ferdig registrert '+new Date().toLocaleString('nb-NO')+'.';};
function renderDerbyConfig(){const d=state.derby;$('derbyType').textContent=d.type;$('dashboardDerbyType').textContent=d.type;$('derbyTaskTotalLabel').textContent=d.taskTotal;$('derbyMaxPoints').textContent=d.maxPoints;$('derbyStrategy').innerHTML=d.strategy.map(x=>'<li>'+esc(x)+'</li>').join('');taskRange.max=d.taskTotal;if(+taskRange.value>d.taskTotal)taskRange.value=d.taskTotal;$('editDerbyType').value=d.type;$('editTaskTotal').value=d.taskTotal;$('editMaxPoints').value=d.maxPoints;$('editStrategy').value=d.strategy.join('\n');progress();}
const editor=$('derbyEditor');$('openDerbyEditor').onclick=()=>showDialog(editor);$('closeDerbyEditor').onclick=()=>closeDialog(editor);$('saveDerby').onclick=()=>{state.derby={type:$('editDerbyType').value.trim()||'Ukjent derby',taskTotal:Math.max(1,+$('editTaskTotal').value||9),maxPoints:Math.max(1,+$('editMaxPoints').value||320),strategy:$('editStrategy').value.split('\n').map(x=>x.trim()).filter(Boolean)};save();renderDerbyConfig();closeDialog(editor);};
renderDerbyConfig();progress();
const hash=location.hash.replace('#','');if(state.currentUserId&&current()&&current().approved){openPortal();if(hash&&hash!=='landing')navigate(hash,false);}
})();
