-- WGANG Portal v0.18.0.11 – Chill Bunny Planner
create table if not exists public.bunny_hare_rounds (
 id bigint generated by default as identity primary key,
 round_no integer not null unique check (round_no between 1 and 3),
 completed_count integer not null default 0 check (completed_count between 0 and 30),
 starts_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now()
);
insert into public.bunny_hare_rounds (round_no,completed_count) values (1,30),(2,0),(3,0)
on conflict (round_no) do nothing;

create table if not exists public.bunny_hare_attendance (
 user_id uuid not null references auth.users(id) on delete cascade,
 round_no integer not null check (round_no between 1 and 3),
 status text not null check (status in ('yes','maybe','no')),
 updated_at timestamptz not null default now(),
 primary key(user_id,round_no)
);
create table if not exists public.bunny_daily_status (
 user_id uuid not null references auth.users(id) on delete cascade,
 derby_day date not null, done boolean not null default false,
 updated_at timestamptz not null default now(), primary key(user_id,derby_day)
);
alter table public.bunny_hare_rounds enable row level security;
alter table public.bunny_hare_attendance enable row level security;
alter table public.bunny_daily_status enable row level security;
grant select,insert,update on public.bunny_hare_rounds to authenticated;
grant select,insert,update,delete on public.bunny_hare_attendance to authenticated;
grant select,insert,update,delete on public.bunny_daily_status to authenticated;
grant usage,select on all sequences in schema public to authenticated;

drop policy if exists "members read hare rounds" on public.bunny_hare_rounds;
create policy "members read hare rounds" on public.bunny_hare_rounds for select to authenticated using(true);
drop policy if exists "members read hare attendance" on public.bunny_hare_attendance;
create policy "members read hare attendance" on public.bunny_hare_attendance for select to authenticated using(true);
drop policy if exists "members manage own hare attendance" on public.bunny_hare_attendance;
create policy "members manage own hare attendance" on public.bunny_hare_attendance for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "members read daily bunny status" on public.bunny_daily_status;
create policy "members read daily bunny status" on public.bunny_daily_status for select to authenticated using(true);
drop policy if exists "members manage own daily bunny status" on public.bunny_daily_status;
create policy "members manage own daily bunny status" on public.bunny_daily_status for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
