-- WGANG Portal v0.18.0.12
-- Roller/rettigheter, endringshistorikk og lesestatus for chat.

create table if not exists public.role_permissions (
  role text not null check (role in ('admin','assistant_leader','member')),
  permission_key text not null,
  enabled boolean not null,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key(role,permission_key)
);

create table if not exists public.permission_audit_log (
  id bigint generated by default as identity primary key,
  role text not null,
  permission_key text not null,
  old_value boolean,
  new_value boolean not null,
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now()
);

create table if not exists public.chat_read_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null,
  last_message_id text,
  last_read_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(user_id,channel)
);

alter table public.role_permissions enable row level security;
alter table public.permission_audit_log enable row level security;
alter table public.chat_read_state enable row level security;

grant select on public.role_permissions to authenticated;
grant select on public.permission_audit_log to authenticated;
grant select,insert,update,delete on public.chat_read_state to authenticated;
grant insert,update,delete on public.role_permissions to authenticated;
grant usage,select on all sequences in schema public to authenticated;

drop policy if exists "authenticated read role permissions" on public.role_permissions;
create policy "authenticated read role permissions"
on public.role_permissions for select to authenticated using(true);

drop policy if exists "owner manages role permissions" on public.role_permissions;
create policy "owner manages role permissions"
on public.role_permissions for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='owner'));

drop policy if exists "admin owner read permission audit" on public.permission_audit_log;
create policy "admin owner read permission audit"
on public.permission_audit_log for select to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','admin')));

drop policy if exists "users read own chat state" on public.chat_read_state;
create policy "users read own chat state"
on public.chat_read_state for select to authenticated using(user_id=auth.uid());

drop policy if exists "users manage own chat state" on public.chat_read_state;
create policy "users manage own chat state"
on public.chat_read_state for all to authenticated
using(user_id=auth.uid()) with check(user_id=auth.uid());

create or replace function public.log_role_permission_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.permission_audit_log(role,permission_key,old_value,new_value,changed_by,changed_at)
  values(new.role,new.permission_key,case when tg_op='UPDATE' then old.enabled else null end,new.enabled,auth.uid(),now());
  return new;
end;
$$;

drop trigger if exists trg_role_permission_audit on public.role_permissions;
create trigger trg_role_permission_audit
after insert or update on public.role_permissions
for each row execute function public.log_role_permission_change();

-- Existing derby_events.id is retained as the canonical Derby-ID/history foundation.
-- We do not duplicate derby history in a second table.
