-- WGANG Portal v0.18.0 – Chill Bunny planner
create table if not exists public.bunny_task_library (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null,
  amount integer not null default 1,
  icon text not null default '🐰',
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.bunny_board (
  id bigint generated by default as identity primary key,
  board_date date not null default current_date,
  published_at timestamptz not null default now(),
  published_by uuid references public.profiles(id),
  active boolean not null default true
);
create table if not exists public.bunny_board_tasks (
  board_id bigint references public.bunny_board(id) on delete cascade,
  task_id bigint references public.bunny_task_library(id) on delete cascade,
  primary key(board_id,task_id)
);
create table if not exists public.bunny_task_status (
  board_id bigint references public.bunny_board(id) on delete cascade,
  task_id bigint references public.bunny_task_library(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  status text not null check(status in ('ready','preparing','skip')),
  updated_at timestamptz not null default now(),
  primary key(board_id,task_id,user_id)
);
alter table public.bunny_task_library enable row level security;
alter table public.bunny_board enable row level security;
alter table public.bunny_board_tasks enable row level security;
alter table public.bunny_task_status enable row level security;

do $$ begin
 create policy "members read bunny library" on public.bunny_task_library for select to authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
 create policy "leadership manage bunny library" on public.bunny_task_library for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','admin','assistant_leader'))) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','admin','assistant_leader')));
exception when duplicate_object then null; end $$;
do $$ begin create policy "members read bunny board" on public.bunny_board for select to authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "leadership manage bunny board" on public.bunny_board for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','admin','assistant_leader'))) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','admin','assistant_leader'))); exception when duplicate_object then null; end $$;
do $$ begin create policy "members read bunny board tasks" on public.bunny_board_tasks for select to authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "leadership manage bunny board tasks" on public.bunny_board_tasks for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','admin','assistant_leader'))) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('owner','admin','assistant_leader'))); exception when duplicate_object then null; end $$;
do $$ begin create policy "members read bunny statuses" on public.bunny_task_status for select to authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "members manage own bunny status" on public.bunny_task_status for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid()); exception when duplicate_object then null; end $$;

insert into public.bunny_task_library(category,name,amount,icon,description)
select * from (values
 ('Bybyggeoppgave','Gjester i Matbutikk',2,'🏪','Ta imot 2 byggjester i Matbutikk'),
 ('Produksjon','Kake med røde bær',3,'🎂','Produser og samle inn 3 kaker med røde bær'),
 ('Innhøsting','Soyabønner',47,'🫛','Høst inn fra 47 soyabønneåkrer'),
 ('Besøkende i byen','Innbygger',1,'🧑‍🌾','Betjen 1 innbygger'),
 ('Innhøsting','Gulrøtter',53,'🥕','Høst inn fra 53 gulrotåkrer'),
 ('Dyreoppgave','Bacon',11,'🥓','Samle 11 bacon'),
 ('Produksjon','Gulrotkake',3,'🍰','Produser og samle inn 3 gulrotkaker'),
 ('Produksjon','Eplejuice',2,'🧃','Produser og samle inn 2 eplejuice'),
 ('Dyreoppgave','Egg',16,'🥚','Samle 16 egg'),
 ('Produksjon','Frutti di Mare-pizza',5,'🍕','Produser og samle inn 5 Frutti di Mare-pizza'),
 ('Innhøsting','Gresskar',38,'🎃','Høst inn fra 38 gresskaråkrer'),
 ('Innhøsting','Hvete',77,'🌾','Høst inn fra 77 hveteåkrer')
) as v(category,name,amount,icon,description)
where not exists(select 1 from public.bunny_task_library);
